### ISSUE TITLE
Error worker install

### ISSUE THREAD

**Issue by ghost** [AlgoSecure/Pollenisator#11]
Hello, 

Here is the error I got while installing the worker. Do you have any idea where this came from?

```bash
docker build --no-cache -t pollenisator .

[...]

Step 41/49 : RUN python3.7 setup.py install
 ---> Running in 5e32feb62e7b
python3.7: can't open file 'setup.py': [Errno 2] No such file or directory
The command '/bin/sh -c python3.7 setup.py install' returned a non-zero code: 2
```

**Comment by fbarre96** [comment]
CrackMapExec install procedure changed over the weekend. We are working on an reliable install procedure for CrackMapExec.

As a temporary fix, you can edit the Dockerfile and remove lines 117 to 123

```
RUN git clone --recursive https://github.com/byt3bl33d3r/CrackMapExec /home/cme/
WORKDIR /home/cme/
RUN python3.7 -m pip install --upgrade pynacl
RUN python3.7 -m pip install --upgrade cryptography
RUN python3.7 -m pip install --upgrade asn1crypto
RUN python3.7 setup.py install
RUN cme smb
```

This mean you will not be able to send crackmapexec commands to the worker but still can use it locally if properly configured.
